import Head from "next/head"
import Navbar from "./navbar"


const Layout = ({ children, title }) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            {children}
        </div>
    )
}

export default Layout
